# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steven Barragán
email: me@steven.xm
description: Steven's personal website
baseurl: ""
url: "http://steven.mx" # the base hostname & protocol for your site
twitter_username: steven_barragan
github_username:  stevenbarragan

# Build settings
markdown: kramdown
